/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Microphone(props) {
    const { nodes, materials } = useGLTF("/microphone/microphone.gltf");
    return (
        <group
            {...props}
            dispose={null}
            scale={[0.1, 0.1, 0.1]}
            position={[0.45, -0.3, 0.4]}
            rotation={[-0.3, 0, 0.2]}
        >
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Microphone_mesh.geometry}
                material={materials.lambert2SG}
            />
        </group>
    );
}

useGLTF.preload("/microphone/microphone.gltf");
