/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Microphone(props) {
    const { nodes, materials } = useGLTF("/microphone/microphone.gltf");
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Microphone_mesh.geometry}
                material={materials.lambert2SG}
            />
        </group>
    );
}

useGLTF.preload("/microphone/microphone.gltf");
