/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import Webplane from "../Webplane";

export function Laptop(props) {
    const { nodes, materials } = useGLTF("/laptop/laptop.gltf");

    var { focuseditem, name } = props;

    var [infocus, setinfocus] = useState();

    useFrame(() => {
        if (focuseditem == name) {
            setinfocus(true);
        } else {
            setinfocus(false);
        }
    });

    return (
        <group
            {...props}
            dispose={null}
            rotation={[0.5, 2.4, -0.2]}
            position={[-2, 0, 0]}
        >
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_0.geometry}
                material={materials.metalDark}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_0_1.geometry}
                material={materials.metal}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_0_2.geometry}
                material={materials.metalMedium}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_1.geometry}
                material={materials.metalMedium}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_1_1.geometry}
                material={materials.metalDark}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_1_2.geometry}
                material={materials.metal}
            />
            {infocus && (
                <group
                    rotation={[0.41, Math.PI, Math.PI]}
                    position={[-0.128, 0.088, 0.2]}
                >
                    <Webplane
                        width={1920}
                        height={1080}
                        distanceFactor={-0.049}
                        src="../index.html"
                    ></Webplane>
                </group>
            )}
        </group>
    );
}

useGLTF.preload("/laptop/laptop.gltf");
