/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import Webplane from "../Webplane";

export function Laptop(props) {
    const { nodes, materials } = useGLTF("/laptop/laptop.gltf");

    var { focuseditem, name } = props;

    var [infocus, setinfocus] = useState();
    var inner = (
        //potentially make this standardized using a class
        <div
            style={{
                width: "100%",
                height: "100%",
                backgroundColor: "black",
                border: "3px solid yellow",
                borderRadius: "50px",
                display: "flex",
                flexDirection: "column",
                justifyContent: "center",
                alignItems: "center",
                color: "white",
            }}
        >
            <h2
                style={{
                    width: "100%",
                    fontSize: "200px",
                    padding: "0px",
                    margin: "auto",
                    flex: 1,
                    textAlign: "center",
                }}
            >
                This Website
            </h2>
            <div
                style={{
                    marginTop: "0px",
                    flex: 2,
                    width: "95%",
                    fontSize: "80px",
                    transform: "TranslateY(-140px)",
                }}
            >
                This website was made using{" "}
                <a
                    className="hovertext"
                    href="https://react.dev/"
                    target="_blank"
                >
                    React
                </a>{" "}
                and{" "}
                <a
                    className="hovertext"
                    href="https://docs.pmnd.rs/react-three-fiber/getting-started/introduction"
                    target="_blank"
                >
                    React-Three-Fiber
                </a>{" "}
                -- an implementaiton of{" "}
                <a
                    className="hovertext"
                    href="https://threejs.org/"
                    target="_blank"
                >
                    Three.js
                </a>{" "}
                in React. I have also encorporated elemets from{" "}
                <a
                    className="hovertext"
                    href="https://www.framer.com/motion/"
                    target="_blank"
                >
                    Framer Motion
                </a>{" "}
                and numerous other libraries. Click{" "}
                <a
                    className="hovertext"
                    href="https://github.com/1112luke/Website-Fiber"
                    target="_blank"
                >
                    HERE
                </a>{" "}
                for a peek at the code.
            </div>
        </div>
    );

    useEffect(() => {
        if (focuseditem == name) {
            setinfocus(true);
        } else {
            setinfocus(false);
        }
    }, [focuseditem]);

    return (
        <group
            {...props}
            dispose={null}
            rotation={[0.5, 2.4, -0.2]}
            position={infocus ? [-4, -3, 0] : [0, 0, 0]}
        >
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_0.geometry}
                material={materials.metalDark}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_0_1.geometry}
                material={materials.metal}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_0_2.geometry}
                material={materials.metalMedium}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_1.geometry}
                material={materials.metalMedium}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_1_1.geometry}
                material={materials.metalDark}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh_1_2.geometry}
                material={materials.metal}
            />
            {infocus && (
                <>
                    <group
                        rotation={[0.41, Math.PI, Math.PI]}
                        position={[-0.128, 0.088, 0.2]}
                    >
                        <Webplane
                            width={1920}
                            height={1080}
                            distanceFactor={-0.049}
                            src="../index.html"
                        ></Webplane>
                    </group>

                    <group
                        rotation={[0.1, 1.25 + Math.PI, Math.PI]}
                        position={[-0.02, 0.14, -0.04]}
                    >
                        <Webplane
                            width={1920}
                            height={1080}
                            distanceFactor={-0.06}
                            inner={inner}
                        ></Webplane>
                    </group>
                </>
            )}
        </group>
    );
}

useGLTF.preload("/laptop/laptop.gltf");
